version: "3.8"

volumes:
  contas_db:

networks:
  default:
    external: true
    name: financas

services:
  db:
    container_name: db
    image: postgres:15-alpine3.17
    pull_policy: always
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - contas_db:/var/lib/postgresql/data
    ports:
      - 5433:5432
  api:
    extends:
      file: apps/api/docker-compose.yml
      service: api
    